version: '3'
services:
  drupal_server:
    container_name: drupal8
    tty: true
    stdin_open: true
    build: .
    ports:
      - '80:80'
      - '8443:443'
      - '8022:22'
      - '3308:3306'
      - '1081:1080'
      - '1026:1025'
    volumes:
#      - 'Project_path':/home/www.drupal8.ma/public_html
      - data:/var/lib/mysql
    environment:
      - VIRTUAL_HOST=dev.drupal
    
volumes:
  data:

